FROM eclipse-temurin:25-jdk as builder
WORKDIR /app
ADD . /app/ai-native
RUN cd ai-native && ./mvnw clean package

FROM eclipse-temurin:25-jre
WORKDIR /app
COPY --from=builder /app/ai-native/target/ai-native-*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/app/app.jar"]